"""auto-vote

Revision ID: 648b88812133
Revises: f84cf0261702
Create Date: 2023-06-19 20:17:19.698339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648b88812133'
down_revision = 'f84cf0261702'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
